### ISSUE TITLE
Testing: Remove adam-test:0.1.0 Chart Version

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [slateci/slate-catalog-incubator#40]
We need a workflow for removing a known chart version from the repository for security reasons.
* Try removing `adam-test:0.1.0` from the Helm repository and document any issues.

**Comment by adamhgriffith-uofu** [comment]
Removing the following in the linked feature branch and deleting the GitHub release does appear to have worked.
```yaml
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-06-08T15:48:34.871305848Z"
    description: A Helm chart for Kubernetes
    digest: d0a2bddd12b35239a1c5f75931dac4ea64d3f6be434355650063a5c6d40c9257
    maintainers:
    - email: adam.h.griffith@utah.edu
      name: adamhgriffith-uofu
    name: adam-test
    type: application
    urls:
    - https://github.com/slateci/slate-catalog-incubator/releases/download/adam-test-0.1.0/adam-test-0.1.0.tgz
    version: 0.1.0
```
Viewed from a client machine:
```shell
$ helm search repo adam-test --versions
NAME                     	CHART VERSION	APP VERSION	DESCRIPTION                
slate-incubator/adam-test	0.1.2        	1.16.2     	A Helm chart for Kubernetes
slate-incubator/adam-test	0.1.1        	1.16.1     	A Helm chart for Kubernetes
slate-incubator/adam-test	0.1.0        	1.16.0     	A Helm chart for Kubernetes
$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "slate-stable" chart repository
...Successfully got an update from the "slate-incubator" chart repository
Update Complete. ⎈Happy Helming!⎈
$ helm search repo adam-test --versions
NAME                     	CHART VERSION	APP VERSION	DESCRIPTION                
slate-incubator/adam-test	0.1.2        	1.16.2     	A Helm chart for Kubernetes
slate-incubator/adam-test	0.1.1        	1.16.1     	A Helm chart for Kubernetes
```
